apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
spec:
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: plaintext
      port: 9092
      targetPort: plaintext
