apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-datasources.yaml
  - configmap-dashboard-provider.yaml
  - configmap-dashboards.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
