apiVersion: v1
kind: ConfigMap
metadata:
  name: producer
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_TOPIC: nyc-taxi-trips
  KAFKA_DLQ_TOPIC: nyc-taxi-trips-dlq
  KAFKA_PRODUCER_ACKS: "all"
  KAFKA_PRODUCER_RETRIES: "5"
  KAFKA_BATCH_SIZE: "500"
  KAFKA_BATCH_TIMEOUT_SECONDS: "10"
  ZONE_LOOKUP_PATH: data/reference/taxi_zone_lookup.csv
  PARQUET_BATCH_SIZE: "1000"
  PROMETHEUS_PORT_PRODUCER: "9100"
  LOG_LEVEL: INFO
