apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nyc-taxi-producer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: nyc-taxi

  source:
    repoURL: "https://github.com/tarique-iqbal/nyc-taxi-gitops.git"
    targetRevision: main
    path: kubernetes/producer/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: etl

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
