apiVersion: v1
kind: ConfigMap
metadata:
  name: health-server
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.kafka.svc.cluster.local:9092
  KAFKA_TOPIC: nyc-taxi-trips
  KAFKA_CONSUMER_GROUP_ID: nyc-taxi-etl-consumer
  CLICKHOUSE_HOST: clickhouse.clickhouse.svc.cluster.local
  CLICKHOUSE_PORT: "9000"
  CLICKHOUSE_DB: taxi
  CLICKHOUSE_USER: default
  HEALTH_PORT: "8000"
  LOG_LEVEL: INFO
